### ISSUE TITLE
Asset bundle files are rendering on the front-end

### ISSUE THREAD

**Issue by marknotton** [wbrowar/craft-little-layout#2]
These asset bundle files are rendering out on the front-end:

`vendor/wbrowar/craft-little-layout/src/assetbundles/dist/assets/little-layout.1c2192e8.css`
`vendor/wbrowar/craft-little-layout/src/assetbundles/dist/assets/little-layout.5fe72174.js`

I only noticed because the Javascript file is jQuery dependent and throws an error on my non-jQuery project:
_Uncaught ReferenceError: jQuery is not defined_ 

Easy solution would be to wrap the bulk of your LittleLayout.php `init` method with a [getIsCpRequest()](https://docs.craftcms.com/api/v3/craft-console-request.html#public-methods) check:

```
if (Craft::$app->getRequest()->getIsCpRequest()) { ... }
```

**Comment by wbrowar** [comment]
Thanks for letting me know, Mark. I'll have that fixed right away.

**Comment by wbrowar** [comment]
Mark, this should be all set in [1.0.1](https://github.com/wbrowar/craft-little-layout/releases/tag/1.0.1). Thanks again for the catch!


I'd love to hear how you’re using your layout fields, so please consider leaving some feedback in [Discussions](https://github.com/wbrowar/craft-little-layout/discussions).

_- Will_
