### ISSUE TITLE
Incompatibility with Quick Field plugin

### ISSUE THREAD

**Issue by marknotton-yello** [wbrowar/craft-little-layout#7]
When I have both Little Layout and the [Spicy Webs Quick Field](https://github.com/spicywebau/craft-quick-field) plugin installed at the same time, the UI completely breaks throughout all of Craft CMS.

![Screenshot 2024-02-20 at 2 08 46 pm](https://github.com/wbrowar/craft-little-layout/assets/153639233/6e0d2905-b8f9-40f2-912c-fb6643bea4a4)

Any click events within the CMS throw errors, making the CMS unusable. My only option is to disable or uninstall one of these plugins.

`./craft plugin/disable little-layout` or `./craft plugin/disable quick-field`

It's hardly a deal-breaking error. In my opinion/experience Quick Fields is generally quite useful for initial project setups and doesn't need to be permanently installed. Also, Craft 5 will be introducing an "[Inline entry type and field creation](https://craftcms.com/blog/craft-5-beta-released#:~:text=Inline%20entry%20type%20and%20field%20creation.%20It%E2%80%99s%20now%20possible%20to%20create%20a%20section%2C%20its%20entry%20types%2C%20and%20custom%20fields%2C%20all%20in%20one%20combined%20workflow%2C%20drastically%20speeding%20up%20content%20modeling.)" utility, which could potentially make Quick Fields obsolete.

Regardless, I thought it was worth sharing in case there are any quick fixes. My tests were done on Craft 4.7.2.1 with PHP 8.3, Little Layout 2.0.0, and Quick Fields 2.0.7.

The reason I've raised the issue with Little Layout instead of Quick Field is because there is no obvious custom JavaScript being used with Quick Field. Their plugin appears to use all native Craft fields and UI components. Also, Little Layout is a paid plugin, whereas theirs is free.

**Comment by wbrowar** [comment]
Hey @marknotton-yello, thanks for all the details. I'll download Quick Fields and see what's going on.

Just to get the full picture, would you mind sharing what browser you're using where you see this error? I'll likely start in the most recent version of Chrome and Firefox, but if it's an older browser compatibility thing I can look into ways to work around that.

**Comment by marknotton-yello** [comment]
Thanks @wbrowar. I'm using the latest version of Chrome on Mac (122.0.6261.57). 

To be honest, this situation is quite niche and unlikely to affect most users, especially considering the features to be offered by Craft 5. I wouldn't be offended if you chose to dismiss and close this issue.

However, if you like weird coding problems to solve, then let me know if you need anything more from me.

**Comment by wbrowar** [comment]
@marknotton-yello, I think I'm going to close this issue. I couldn't figure it out on Craft 4 after spending a little time trying to figure it out and since the Quick Field plugin isn't moving to Craft 5 then I'll leave this alone.

Thanks for your patience and for bringing this issue in the first place!
